const KEY='arvinFitV1';
const targets={kcal:2000,protein:140,carb:210,fat:65,startWeight:75,goalWeight:70};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{meals:{},recipes:[],weights:{},gymDays:[],avatar:{muscle:55,shoulders:55,waist:50,definition:45}};
const $=id=>document.getElementById(id); const today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function dayMeals(d=today()){return state.meals[d]||[]}
function totals(d=today()){return dayMeals(d).reduce((a,m)=>({kcal:a.kcal+m.kcal,protein:a.protein+m.protein,carb:a.carb+m.carb,fat:a.fat+m.fat}),{kcal:0,protein:0,carb:0,fat:0})}
function fmtDate(d=new Date()){return d.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function addMealObj(m,d=today()){state.meals[d]=state.meals[d]||[];state.meals[d].push(m);save();avatarSay(m.protein>=25?'Bel colpo proteico. Pollice in su!':'Pasto registrato. La costanza vince.');}
function avatarSay(t){$('avatarMood').textContent=t;$('avatarFigure').animate([{transform:'translateY(0) rotate(0)'},{transform:'translateY(-14px) rotate(-2deg)'},{transform:'translateY(0)'}],{duration:700,easing:'ease-out'})}
let charts={};
function chart(id,type,data,options={}){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data,options:{responsive:true,plugins:{legend:{labels:{color:'#f7f8fb'}}},scales:type==='doughnut'?{}:{x:{ticks:{color:'#aeb4c4'},grid:{color:'rgba(255,255,255,.08)'}},y:{ticks:{color:'#aeb4c4'},grid:{color:'rgba(255,255,255,.08)'}}},...options}})}
function lastDays(n){return [...Array(n)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(n-1-i));return d.toISOString().slice(0,10)})}
function render(){const t=totals();$('todayLabel').textContent=fmtDate();$('caloriesNow').textContent=Math.round(t.kcal);$('proteinNow').textContent=Math.round(t.protein)+'g';$('carbNow').textContent=Math.round(t.carb)+'g';$('fatNow').textContent=Math.round(t.fat)+'g';$('calorieRing').style.width=Math.min(100,t.kcal/targets.kcal*100)+'%';
const currentWeight=Number(state.weights[today()]||Object.values(state.weights).at(-1)||targets.startWeight); const prog=(targets.startWeight-currentWeight)/(targets.startWeight-targets.goalWeight)*100;$('goalProgress').style.width=Math.max(0,Math.min(100,prog))+'%';
$('mealList').innerHTML=dayMeals().map((m,i)=>`<div class="item"><div><strong>${m.name}</strong><br><small>${m.kcal} kcal · P ${m.protein}g · C ${m.carb}g · G ${m.fat}g</small></div><button class="ghost" onclick="removeMeal(${i})">Elimina</button></div>`).join('')||'<p class="muted">Nessun pasto inserito oggi.</p>';
$('recipeGrid').innerHTML=state.recipes.map((r,i)=>`<div class="recipe-card"><strong>${r.name}</strong><p class="muted">${r.kcal} kcal · P ${r.protein}g · C ${r.carb}g · G ${r.fat}g</p><button class="primary" onclick="useRecipe(${i})">Aggiungi a oggi</button><button class="ghost" onclick="deleteRecipe(${i})">Elimina</button></div>`).join('')||'<p class="muted">Nessuna ricetta salvata.</p>';
chart('macroChart','doughnut',{labels:['Proteine','Carboidrati','Grassi'],datasets:[{data:[t.protein*4,t.carb*4,t.fat*9]}]},{cutout:'68%'});
const ds=lastDays(7), wk=ds.map(d=>totals(d).kcal); chart('weekChart','line',{labels:ds.map(d=>new Date(d).toLocaleDateString('it-IT',{weekday:'short'})),datasets:[{label:'kcal',data:wk,tension:.45,fill:true}]});
const wdates=Object.keys(state.weights).sort(); chart('weightChart','line',{labels:wdates.map(d=>new Date(d).toLocaleDateString('it-IT',{day:'2-digit',month:'2-digit'})),datasets:[{label:'Peso kg',data:wdates.map(d=>state.weights[d]),tension:.45}]});
$('progressSummary').innerHTML=`Peso attuale stimato: <strong>${currentWeight.toFixed(1)} kg</strong><br>Mancano <strong>${Math.max(0,currentWeight-targets.goalWeight).toFixed(1)} kg</strong> all'obiettivo.<br>Calorie oggi: <strong>${Math.round(t.kcal)}</strong> su ${targets.kcal}.`;
applyAvatar();}
function applyAvatar(){const a=state.avatar;document.documentElement.style.setProperty('--dummy','1');const torso=document.querySelector('.torso');const avatar=$('avatarFigure');torso.style.width=(78+a.shoulders*.35)+'px';torso.style.left=(80-(78+a.shoulders*.35)/2)+'px';torso.style.transform=`scaleX(${.9+a.waist/220})`;avatar.style.filter=`drop-shadow(0 25px 30px rgba(0,0,0,.35)) saturate(${.8+a.definition/120})`;}
window.removeMeal=i=>{state.meals[today()].splice(i,1);save()}; window.useRecipe=i=>addMealObj({...state.recipes[i]}); window.deleteRecipe=i=>{state.recipes.splice(i,1);save()};
document.querySelectorAll('.nav,[data-view-jump]').forEach(b=>b.onclick=()=>{const v=b.dataset.view||b.dataset.viewJump;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===v)); if(v==='progress') avatarSay('Guardiamo i dati: conta la media, non il singolo giorno.');});
$('addMeal').onclick=()=>{const m={name:$('mealName').value||'Pasto',kcal:+$('mealKcal').value||0,protein:+$('mealProtein').value||0,carb:+$('mealCarb').value||0,fat:+$('mealFat').value||0};addMealObj(m);['mealName','mealKcal','mealProtein','mealCarb','mealFat'].forEach(id=>$(id).value='')};
$('addRecipe').onclick=()=>{state.recipes.push({name:$('recipeName').value||'Ricetta',kcal:+$('recipeKcal').value||0,protein:+$('recipeProtein').value||0,carb:+$('recipeCarb').value||0,fat:+$('recipeFat').value||0});['recipeName','recipeKcal','recipeProtein','recipeCarb','recipeFat'].forEach(id=>$(id).value='');save()};
$('seedRecipes').onclick=()=>{state.recipes=[...state.recipes,{name:'Hamburger tacchino air fryer',kcal:620,protein:52,carb:55,fat:18},{name:'Tonno insalata e pane',kcal:480,protein:38,carb:52,fat:12},{name:'French toast integrale',kcal:430,protein:28,carb:45,fat:14},{name:'Pasta gamberi weekend',kcal:760,protein:42,carb:92,fat:20},{name:'Noodles + pollo',kcal:650,protein:34,carb:78,fat:21}];save()};
$('saveWeight').onclick=()=>{state.weights[today()]=+$('weightInput').value||targets.startWeight;save();avatarSay('Peso aggiornato. L’avatar evolve gradualmente con te.');};
['muscle','shoulders','waist','definition'].forEach(id=>$(id).oninput=e=>{state.avatar[id]=+e.target.value;save()});
const labels=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'];$('gymDays').innerHTML=labels.map(x=>`<div class="day">${x}</div>`).join('');document.querySelectorAll('.day').forEach((d,i)=>{d.onclick=()=>d.classList.toggle('active')});$('saveGymDays').onclick=()=>{state.gymDays=[...document.querySelectorAll('.day')].map((d,i)=>d.classList.contains('active')?labels[i]:null).filter(Boolean);$('weeklyMessage').innerHTML=`Impegno salvato: <strong>${state.gymDays.join(', ')||'nessun giorno selezionato'}</strong>.<br>L'avatar te lo ricorderà nei giorni giusti.`;avatarSay('Perfetto. Ora abbiamo un piano per la settimana.');save()};
$('resetDemo').onclick=()=>{localStorage.removeItem(KEY);location.reload()};
if(new Date().getDay()===0) avatarSay('È domenica: facciamo il check-in e scegliamo i giorni palestra?');render();
