function renderDiary(){
 const d=state.selectedDate||todayISO(); const meals=mealsFor(d), s=sumMacros(meals), t=profileTargets();
 $('#diary').innerHTML=`<div class="grid two"><div class="card"><p class="eyebrow">Diario</p><h2>${prettyDate(d)}</h2><div class="form-grid"><div class="field"><label>Giorno</label><input type="date" id="diaryDate" value="${d}"></div><div class="field"><label>&nbsp;</label><button class="primary" data-action="quickMeal">+ Pasto</button></div></div></div><div class="metric-row">${ringHTML('kcal',s.kcal,t.target,'var(--green)')}${ringHTML('proteine',s.protein,t.protein,'var(--violet)')}${ringHTML('carbo',s.carbs,t.carbs,'var(--blue)')}${ringHTML('grassi',s.fat,t.fat,'var(--amber)')}</div></div><br><div class="card"><h2>Pasti</h2><div class="list">${meals.length?meals.map(mealItem).join(''):'<p class="muted">Nessun pasto per questo giorno.</p>'}</div></div>`;
 $('#diaryDate').onchange=e=>{state.selectedDate=e.target.value;saveState();renderDiary();};
}
function quickMealModal(){
 const options=allFoods().map(f=>`<option value="${f.name}">${f.name}</option>`).join('');
 openModal(`<h2>Aggiungi pasto</h2><div class="form-grid"><div class="field"><label>Data</label><input id="mealDate" type="date" value="${state.selectedDate||todayISO()}"></div><div class="field"><label>Tipo</label><select id="mealType"><option>Pranzo</option><option>Cena</option><option>Spuntino</option><option>Altro</option></select></div><div class="field"><label>Alimento</label><input id="foodName" list="foodsList" placeholder="Es. Hamburger pollo"><datalist id="foodsList">${options}</datalist></div><div class="field"><label>Grammi/ml</label><input id="foodGrams" type="number" value="100"></div></div><p class="hint">Se l'alimento non esiste, puoi inserirlo dalla pagina Impostazioni.</p><br><button class="primary" id="addMealBtn">Aggiungi</button>`);
 $('#addMealBtn').onclick=()=>{ const name=$('#foodName').value, grams=Number($('#foodGrams').value); const calc=calcIngredient(name,grams); if(!calc){toast('Alimento non trovato');return} state.meals.push({id:uid(),date:$('#mealDate').value,type:$('#mealType').value,...calc}); saveState(); closeModal(); renderAll(); toast('Pasto aggiunto'); };
}
