'use client';
import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CalendarDays, Dumbbell, Plus, Save, User, Utensils, TrendingDown, Download, Upload } from 'lucide-react';
import { Meal, Profile, WeightEntry, GymDay } from '@/lib/types';

type Tab = 'dashboard'|'profile'|'diary'|'recipes'|'calendar'|'progress';
const today = () => new Date().toISOString().slice(0,10);
const uid = () => Math.random().toString(36).slice(2,10);
const defaultProfile: Profile = { age:27, sex:'male', height:175, startWeight:75, currentWeight:75, goalWeight:70, workoutsPerWeek:3, activity:'medium', targetCalories:2100, proteinTarget:140, carbTarget:210, fatTarget:65 };
const recipes = [
  {name:'Hamburger tacchino air fryer', kcal:520, protein:45, carbs:42, fat:17},
  {name:'Tonno pane e insalata', kcal:430, protein:36, carbs:48, fat:9},
  {name:'French toast integrale', kcal:470, protein:30, carbs:52, fat:15},
  {name:'Noodles + tonno', kcal:590, protein:35, carbs:78, fat:16}
];
function kcalTarget(p:Profile){ const bmr = p.sex==='male' ? 10*p.currentWeight+6.25*p.height-5*p.age+5 : 10*p.currentWeight+6.25*p.height-5*p.age-161; const mult = p.activity==='low'?1.35:p.activity==='high'?1.7:1.55; return Math.round(bmr*mult-500); }
function macroFromCalories(kcal:number, weight:number){ const protein=Math.round(weight*1.9); const fat=Math.round(weight*.85); const carbs=Math.round((kcal-protein*4-fat*9)/4); return {protein, fat, carbs: Math.max(carbs,80)}; }
function Ring({label,value,target,color,unit='g'}:{label:string;value:number;target:number;color:string;unit?:string}){ const pct=Math.min(100, Math.round(value/Math.max(target,1)*100)); return <div className="glass rounded-[28px] p-4 shadow-soft"><div className="ringbar mx-auto grid h-24 w-24 place-items-center rounded-full" style={{'--p':pct,'--c':color} as any}><div className="grid h-20 w-20 place-items-center rounded-full bg-white/90 text-center"><b>{pct}%</b><span className="text-[11px] text-slate-500">{label}</span></div></div><p className="mt-3 text-center text-sm font-semibold">{value}{unit} / {target}{unit}</p></div> }
export default function App(){
 const [tab,setTab]=useState<Tab>('dashboard'); const [profile,setProfile]=useState<Profile>(defaultProfile); const [meals,setMeals]=useState<Meal[]>([]); const [weights,setWeights]=useState<WeightEntry[]>([]); const [gym,setGym]=useState<GymDay[]>([]); const [date,setDate]=useState(today());
 useEffect(()=>{ const raw=localStorage.getItem('smyprime-v2'); if(raw){ const d=JSON.parse(raw); setProfile(d.profile||defaultProfile); setMeals(d.meals||[]); setWeights(d.weights||[]); setGym(d.gym||[]); }},[]);
 useEffect(()=>{ localStorage.setItem('smyprime-v2',JSON.stringify({profile,meals,weights,gym})); },[profile,meals,weights,gym]);
 const dayMeals=meals.filter(m=>m.date===date); const totals=dayMeals.reduce((a,m)=>({kcal:a.kcal+m.kcal,protein:a.protein+m.protein,carbs:a.carbs+m.carbs,fat:a.fat+m.fat}),{kcal:0,protein:0,carbs:0,fat:0}); const deficit=profile.targetCalories-totals.kcal;
 const last7=[...Array(7)].map((_,i)=>{ const d=new Date(); d.setDate(d.getDate()-6+i); const ds=d.toISOString().slice(0,10); const kcal=meals.filter(m=>m.date===ds).reduce((s,m)=>s+m.kcal,0); return {day:d.toLocaleDateString('it-IT',{weekday:'short'}), kcal, deficit:profile.targetCalories-kcal}; });
 const nav=[['dashboard','Oggi'],['profile','Profilo'],['diary','Diario'],['recipes','Ricettario'],['calendar','Calendario'],['progress','Progressi']] as [Tab,string][];
 function addMeal(base?:any){ const name=base?.name || (document.getElementById('mealName') as HTMLInputElement)?.value || 'Pasto'; const kcal=+(base?.kcal ?? (document.getElementById('kcal') as HTMLInputElement)?.value || 0); const protein=+(base?.protein ?? (document.getElementById('protein') as HTMLInputElement)?.value || 0); const carbs=+(base?.carbs ?? (document.getElementById('carbs') as HTMLInputElement)?.value || 0); const fat=+(base?.fat ?? (document.getElementById('fat') as HTMLInputElement)?.value || 0); setMeals([{id:uid(),date,name,kcal,protein,carbs,fat,mealType:'pasto'},...meals]); }
 function recalc(){ const t=kcalTarget(profile); const m=macroFromCalories(t, profile.currentWeight); setProfile({...profile,targetCalories:t,proteinTarget:m.protein,carbTarget:m.carbs,fatTarget:m.fat}); }
 function exportData(){ const blob=new Blob([JSON.stringify({profile,meals,weights,gym},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='show-me-your-prime-backup.json'; a.click(); }
 return <main className="min-h-screen p-3 md:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold text-emerald-600">{new Date().toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><h1 className="text-3xl font-black tracking-tight md:text-5xl">Show Me Your Prime</h1><p className="text-slate-500">Another Time</p></div><button onClick={exportData} className="glass rounded-2xl px-4 py-3 font-bold"><Download className="inline h-4"/> Backup</button></header><div className="grid gap-5 md:grid-cols-[220px_1fr]"><aside className="glass rounded-[32px] p-3 md:sticky md:top-6 md:h-fit">{nav.map(n=><button key={n[0]} onClick={()=>setTab(n[0])} className={`mb-2 w-full rounded-2xl px-4 py-3 text-left font-bold ${tab===n[0]?'bg-slate-950 text-white':'hover:bg-white'}`}>{n[1]}</button>)}</aside><section>{tab==='dashboard'&&<div className="space-y-5"><div className="glass rounded-[36px] p-6 md:p-9"><h2 className="text-3xl font-black">Dashboard</h2><p className="text-slate-500">Controllo giornaliero di calorie, macro, peso e progressi.</p><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><Ring label="kcal" value={totals.kcal} target={profile.targetCalories} unit="" color="#8b5cf6"/><Ring label="proteine" value={totals.protein} target={profile.proteinTarget} color="#10b981"/><Ring label="carbo" value={totals.carbs} target={profile.carbTarget} color="#60a5fa"/><Ring label="grassi" value={totals.fat} target={profile.fatTarget} color="#f59e0b"/></div></div><div className="grid gap-5 md:grid-cols-2"><Chart title="Ultimi 7 giorni" data={last7} k="kcal"/><Chart title="Deficit ultimi 7 giorni" data={last7} k="deficit"/></div></div>}
 {tab==='profile'&&<Card title="Profilo"><div className="grid gap-3 md:grid-cols-3">{[['age','Età'],['height','Altezza cm'],['startWeight','Peso partenza'],['currentWeight','Peso attuale'],['goalWeight','Peso obiettivo'],['workoutsPerWeek','Allenamenti/settimana']].map(([key,label])=><label key={key} className="font-bold text-sm">{label}<input type="number" value={(profile as any)[key]} onChange={e=>setProfile({...profile,[key]:+e.target.value})} className="mt-1 w-full rounded-2xl border p-3"/></label>)}<label className="font-bold text-sm">Sesso<select value={profile.sex} onChange={e=>setProfile({...profile,sex:e.target.value as any})} className="mt-1 w-full rounded-2xl border p-3"><option value="male">Uomo</option><option value="female">Donna</option></select></label><label className="font-bold text-sm">Attività<select value={profile.activity} onChange={e=>setProfile({...profile,activity:e.target.value as any})} className="mt-1 w-full rounded-2xl border p-3"><option value="low">Bassa</option><option value="medium">Media</option><option value="high">Alta</option></select></label></div><button onClick={recalc} className="mt-5 rounded-2xl bg-slate-950 px-5 py-3 font-bold text-white">Calcola calorie e macro</button><p className="mt-4 text-slate-600">Target: <b>{profile.targetCalories} kcal</b>, proteine <b>{profile.proteinTarget}g</b>, carbo <b>{profile.carbTarget}g</b>, grassi <b>{profile.fatTarget}g</b>.</p></Card>}
 {tab==='diary'&&<Card title="Diario alimentare"><DatePicker date={date} setDate={setDate}/><div className="mt-4 grid gap-2 md:grid-cols-5"><input id="mealName" placeholder="Nome pasto" className="rounded-2xl border p-3"/><input id="kcal" placeholder="kcal" type="number" className="rounded-2xl border p-3"/><input id="protein" placeholder="proteine" type="number" className="rounded-2xl border p-3"/><input id="carbs" placeholder="carbo" type="number" className="rounded-2xl border p-3"/><input id="fat" placeholder="grassi" type="number" className="rounded-2xl border p-3"/></div><button onClick={()=>addMeal()} className="mt-3 rounded-2xl bg-emerald-500 px-5 py-3 font-bold text-white"><Plus className="inline h-4"/> Aggiungi</button><MealList meals={dayMeals}/></Card>}
 {tab==='recipes'&&<Card title="Ricettario"> <div className="grid gap-3 md:grid-cols-2">{recipes.map(r=><div key={r.name} className="rounded-3xl bg-white p-4 shadow-sm"><h3 className="font-black">{r.name}</h3><p className="text-slate-500">{r.kcal} kcal · P {r.protein} · C {r.carbs} · G {r.fat}</p><button onClick={()=>addMeal(r)} className="mt-3 rounded-2xl bg-slate-950 px-4 py-2 font-bold text-white">Aggiungi a oggi</button></div>)}</div></Card>}
 {tab==='calendar'&&<Card title="Calendario palestra e giorno"><DatePicker date={date} setDate={setDate}/><div className="mt-4 flex gap-2"><button onClick={()=>setGym([{id:uid(),date,planned:true,done:false},...gym])} className="rounded-2xl bg-violet-500 px-4 py-3 font-bold text-white">Programma palestra</button><button onClick={()=>setGym([{id:uid(),date,planned:false,done:true},...gym])} className="rounded-2xl bg-emerald-500 px-4 py-3 font-bold text-white">Segna fatta</button></div><p className="mt-4 font-bold">Dettaglio {date}: {totals.kcal} kcal · deficit {deficit}</p><MealList meals={dayMeals}/></Card>}
 {tab==='progress'&&<div className="grid gap-5"><Chart title="Peso" data={weights.map(w=>({day:w.date,weight:w.weight}))} k="weight" area/><Chart title="Calorie settimanali" data={last7} k="kcal"/><Chart title="Deficit settimanale" data={last7} k="deficit"/><Card title="Aggiungi peso"><DatePicker date={date} setDate={setDate}/><input id="newWeight" type="number" step="0.1" placeholder="Peso" className="mt-3 rounded-2xl border p-3"/><button onClick={()=>{ const w=+(document.getElementById('newWeight') as HTMLInputElement).value; setWeights([{id:uid(),date,weight:w},...weights]); setProfile({...profile,currentWeight:w}); }} className="ml-2 rounded-2xl bg-slate-950 px-4 py-3 font-bold text-white">Salva peso</button></Card></div>}</section></div></div></main>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="glass rounded-[36px] p-6 shadow-soft"><h2 className="mb-4 text-3xl font-black">{title}</h2>{children}</div>}
function DatePicker({date,setDate}:{date:string;setDate:(d:string)=>void}){return <input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-2xl border bg-white p-3 font-bold"/>}
function MealList({meals}:{meals:Meal[]}){return <div className="mt-5 space-y-2">{meals.map(m=><div key={m.id} className="rounded-2xl bg-white p-3"><b>{m.name}</b><span className="text-slate-500"> · {m.kcal} kcal · P {m.protein} C {m.carbs} G {m.fat}</span></div>)}</div>}
function Chart({title,data,k,area=false}:{title:string;data:any[];k:string;area?:boolean}){return <div className="glass h-80 rounded-[36px] p-6 shadow-soft"><h2 className="text-2xl font-black">{title}</h2><ResponsiveContainer width="100%" height="82%">{area?<AreaChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Area dataKey={k} /></AreaChart>:<BarChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey={k} radius={[12,12,0,0]}/></BarChart>}</ResponsiveContainer></div>}
